name: "Test"

# actions-up-ignore-file

on:
  workflow_dispatch:
  #schedule:
  #  - cron: "18 18 * * 1,3,5"
  #push:
  #  branches: [master]
  #  paths:
  #    - "dist/**"
  #    - "src/**"
  #    - ".github/workflows/test.yaml"
  #    - "package*.json"
  #    - "requirements*.txt"
  #    - "action.yml"
  #pull_request:

env:
  crawler-id: "740ca24d-65fd-4f25-b397-16ebcec2f7fd" # django-files-docs

jobs:
  test:
    name: "Test"
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: "Checkout"
        uses: actions/checkout@v5

      - name: "Debug CTX github"
        if: ${{ !github.event.act }}
        continue-on-error: true
        env:
          GITHUB_CTX: ${{ toJSON(github) }}
        run: echo "$GITHUB_CTX"

      - name: "Debug Environment"
        if: ${{ !github.event.act }}
        continue-on-error: true
        run: |
          env

      - name: "Test Local Action"
        if: ${{ env.crawler-id != '' }}
        id: test
        uses: ./
        with:
          crawler_id: ${{ env.crawler-id }}
          #crawler_id: ${{ secrets.CRAWLER_ID }}
          crawler_user_id: ${{ secrets.CRAWLER_USER_ID }}
          crawler_api_key: ${{ secrets.CRAWLER_API_KEY }}

      - name: "Debug test.outputs"
        #if: ${{ !github.event.act }}
        continue-on-error: true
        env:
          GITHUB_CTX: ${{ toJSON(steps.test.outputs) }}
        run: echo "$GITHUB_CTX"

      - name: "Verify Outputs"
        run: |
          echo '${{ steps.test.outputs.status }}'
          echo '${{ steps.test.outputs.task_id }}'
          if [ -z '${{ steps.test.outputs.task_id }}' ];then
            echo "Missing output: task_id"
            exit 1
          fi

      - name: "Schedule Failure Notification"
        if: ${{ failure() && github.event_name == 'schedule' }}
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
